// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-utSBSGeseqzPcXvRiIJxD-JH1DXpQ4',
    appId: '1:275827649853:web:81b5625d7231a8b9442954',
    messagingSenderId: '275827649853',
    projectId: 'comandaplay',
    authDomain: 'comandaplay.firebaseapp.com',
    storageBucket: 'comandaplay.firebasestorage.app',
    measurementId: 'G-TBRLBMKR03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0gCyy_82opfUh1MEDYPsfffwPgd0uCIU',
    appId: '1:275827649853:android:06be6cf2a08c3d0d442954',
    messagingSenderId: '275827649853',
    projectId: 'comandaplay',
    storageBucket: 'comandaplay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHZQRkSRlDKE7Trg-KlBl3lWwUJABFI0',
    appId: '1:275827649853:ios:adccf7d43e2dd172442954',
    messagingSenderId: '275827649853',
    projectId: 'comandaplay',
    storageBucket: 'comandaplay.firebasestorage.app',
    androidClientId: '275827649853-2vdlf335cgfp6573vfvaapi46dsjbn10.apps.googleusercontent.com',
    iosClientId: '275827649853-t8rrcckacnv1em0aroo48ri0vtl8mson.apps.googleusercontent.com',
    iosBundleId: 'com.example.arenaComanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHZQRkSRlDKE7Trg-KlBl3lWwUJABFI0',
    appId: '1:275827649853:ios:adccf7d43e2dd172442954',
    messagingSenderId: '275827649853',
    projectId: 'comandaplay',
    storageBucket: 'comandaplay.firebasestorage.app',
    androidClientId: '275827649853-2vdlf335cgfp6573vfvaapi46dsjbn10.apps.googleusercontent.com',
    iosClientId: '275827649853-t8rrcckacnv1em0aroo48ri0vtl8mson.apps.googleusercontent.com',
    iosBundleId: 'com.example.arenaComanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM-utSBSGeseqzPcXvRiIJxD-JH1DXpQ4',
    appId: '1:275827649853:web:3a123ec22846ae17442954',
    messagingSenderId: '275827649853',
    projectId: 'comandaplay',
    authDomain: 'comandaplay.firebaseapp.com',
    storageBucket: 'comandaplay.firebasestorage.app',
    measurementId: 'G-8J9B43Z9VE',
  );

}